### PR TITLE
Authorize() returns optional reason string for client

### PR DESCRIPTION
**Pull request by gammazero**
If `Authorize()` returns false, an optional reason string may be returned to provide additional information to the client about the unauthorized response, or the authorization failure.

This is a API change, so need to consider carefully.

### CODE REVIEW

**Comment by mourad** [comment]
Instead of changing the interface to return an optional string, have you considered returning a specific `error` that could carry the reason itself?

**Comment by gammazero** [comment]
Currently, the presence of error is used to differentiate between not authz and failed authz.  If I understand what you are suggesting it is to have `Authorize()` return an `AuthzError` type of error (and type assert the error into that type).  The AuthzError would contain both the error type (`not_authorized`, or `authorization_failed`) and an optional message?

In the case of authz failure, the error may contain information that gets logged, but is not meant for the client (i.e. info concerning the inner workings of the authz provided).  The optional reason message is one that is meant for the client specifically, so the `AuthzError` would  need to contain 3 items:
1. error type
2. error message
3. optional reason message

This would make the boolean returned by `Authorize()` unnecessary, since that could now be determined by `if err != nil`

**Comment by gammazero** [comment]
It may be a bad thing to encourage sending reason info back in a `not_authorized` response, since that risks disclosing information that could help an attacker's efforts to probe (e.g. "this user is not an admin").  Maybe better to limit returning error information to `authorization_failed` response, since that is a case where authorization could not be determined (e.g. could not connect to policy DB).

**Comment by mourad** [comment]
I agree that `authorization_failed` would be a better place to return a reason.

**Comment by mourad** [comment]
LGTM

**Pull request merged**
