### PR TITLE
Added go modules and removed vendoring folder

### PR DESCRIPTION
**Pull request by johannwagner**
Hey,

I just wanted to work on this project again and thought, that it would be a good idea to migrate this project to go modules.

### CODE REVIEW

**Comment by johannwagner** [comment]
Go Modules are working with Go 1.11 and up. The older versions will fail. You may want to remove them. 

I will fix the CI issues ASAP.

**Comment by johannwagner** [comment]
Oh, I can edit the `.travis.yml`. Ignore my last comment, I will take care of the issues.

**Comment by johannwagner** [comment]
@ajgillis @gammazero CI is fixed.

**Comment by ajgillis** [comment]
LGTM

**Comment by gammazero** [comment]
LGTM

**Pull request merged**
